# Generated by Django 4.0.3 on 2022-03-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_remove_manager_email_remove_manager_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Product Barcode', max_length=13)),
                ('title', models.CharField(help_text='Product Title', max_length=200)),
                ('description', models.TextField(help_text='Product Description')),
                ('price', models.FloatField(help_text='Product Cost')),
                ('quantity', models.FloatField(help_text='Enter Product Quantity')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.company')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Store Name', max_length=200)),
                ('address', models.TextField(help_text='Store address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.company')),
                ('products', models.ManyToManyField(to='datastore.product')),
            ],
        ),
    ]
